package com.yourname.ayanami.learn.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf
import com.yourname.ayanami.learn.data.local.ActivityStatus
import com.yourname.ayanami.learn.data.local.NativeLanguage

data class AppStrings(
    val settings: String,
    val edit: String,
    val save: String,
    val profile: String,
    val editProfile: String,
    val displayName: String,
    val bio: String,
    val nativeLanguage: String,
    val activityStatus: String,
    val rememberThisSetting: String,
    val learning: String,
    val preferences: String,
    val accountAndSupport: String,
    val dailyGoal: String,
    val minutesPerDay: (Int) -> String,
    val voiceReplies: String,
    val speakingExercises: String,
    val studyReminders: String,
    val soundEffects: String,
    val darkMode: String,
    val ayanamiTheme: String,
    val aiMode: String,
    val choosePractice: String,
    val voiceAi: String,
    val voiceAiDescription: String,
    val textAi: String,
    val textAiDescription: String,
    val aiVoiceTile: String,
    val aiChatTile: String,
    val ayanamiLive: String,
    val ayanamiLearnAi: String,
    val messagePlaceholder: String,
    val viewProfile: String,
    val voiceListening: String,
    val voiceThinking: String,
    val voiceSpeaking: String,
    val voiceConnecting: String,
    val voiceReady: String,
    val startLesson: String,
    val voiceMic: String,
    val voiceEnd: String,
    val voiceHintReady: String,
    val voiceHintListening: String,
    val voiceHintSpeaking: String,
    val voiceHintConnecting: String,
    val settingsTab: String,
    val homeTab: String,
    val practiceTab: String,
    val leaguesTab: String,
    val aiTab: String,
    val connectGoogle: String,
    val disconnectGoogle: String,
    val connectGithub: String,
    val disconnectGithub: String,
    val connected: String,
    val notConnected: String,
    val appDiagnostics: String,
    val about: String,
    val logout: String,
    val completeYourProfile: String,
    val profilePhoto: String,
    val changePhoto: String,
    val statusOnline: String,
    val statusIdle: String,
    val statusOffline: String,
    val profileSaved: String,
    val googleIdTokenMissing: String,
    val googleSignInFailed: String,
    val googleConnectedMessage: String,
    val googleDisconnectedMessage: String,
    val githubConnectedMessage: String,
    val githubDisconnectedMessage: String,
    val accountActionFailed: String,
    val sessionRequired: String,
    val authWelcomePrefix: String,
    val authTagline: String,
    val authEmail: String,
    val authPassword: String,
    val authForgotPassword: String,
    val authSignIn: String,
    val authNoAccount: String,
    val authCreateFreeAccount: String,
    val authSignInWithGoogle: String,
    val authCreateWithGoogle: String,
    val authConnecting: String,
    val authLetsStart: String,
    val authAlmostThere: String,
    val authStepOneDescription: String,
    val authStepTwoDescription: String,
    val authFullName: String,
    val authContinue: String,
    val authCreateAccount: String,
    val authCreatingAccount: String,
    val authPasswordResetEmailRequired: String,
    val authPasswordResetEmailSent: (String) -> String,
    val authPasswordResetFailed: String,
    val authFailed: String,
    val appVersion: (String) -> String,
    val signedInAs: (String) -> String,
    val firebaseSession: (Boolean) -> String
) {
    fun statusLabel(status: ActivityStatus): String {
        return when (status) {
            ActivityStatus.Online -> statusOnline
            ActivityStatus.Idle -> statusIdle
            ActivityStatus.Offline -> statusOffline
        }
    }
}

val PortugueseStrings = AppStrings(
    settings = "Definições",
    edit = "Editar",
    save = "Guardar",
    profile = "Perfil",
    editProfile = "Editar perfil",
    displayName = "Nome de utilizador",
    bio = "Bio",
    nativeLanguage = "Língua nativa",
    activityStatus = "Status de atividade",
    rememberThisSetting = "Lembrar desta configuração",
    learning = "Aprendizado",
    preferences = "Preferências",
    accountAndSupport = "Conta e suporte",
    dailyGoal = "Objetivo diário",
    minutesPerDay = { "$it minutos por dia" },
    voiceReplies = "Respostas por voz",
    speakingExercises = "Exercícios de fala",
    studyReminders = "Lembretes de estudo",
    soundEffects = "Efeitos sonoros",
    darkMode = "Modo escuro",
    ayanamiTheme = "Tema visual Ayanami",
    aiMode = "Modo IA",
    choosePractice = "Escolha como quer praticar hoje",
    voiceAi = "Falar com Ayanami Live",
    voiceAiDescription = "Conversação por voz em tempo real",
    textAi = "Mandar mensagem",
    textAiDescription = "Pratique escrita e dúvidas via chat",
    aiVoiceTile = "Voz ao vivo",
    aiChatTile = "Chat",
    ayanamiLive = "Ayanami Live",
    ayanamiLearnAi = "Ayanami Learn AI",
    messagePlaceholder = "Mensagem...",
    viewProfile = "Ver perfil",
    voiceListening = "Ouvindo...",
    voiceThinking = "Pensando...",
    voiceSpeaking = "Falando",
    voiceConnecting = "Conectando",
    voiceReady = "Pronto",
    startLesson = "COMEÇAR",
    voiceMic = "Microfone",
    voiceEnd = "Encerrar",
    voiceHintReady = "Toque no microfone e comece a falar",
    voiceHintListening = "Toque de novo quando terminar de falar",
    voiceHintSpeaking = "Toque no microfone para interromper",
    voiceHintConnecting = "Conectando com a Ayanami...",
    settingsTab = "Ajustes",
    homeTab = "Jornada",
    practiceTab = "Prática",
    leaguesTab = "Ligas",
    aiTab = "IA",
    connectGoogle = "Conectar Google",
    disconnectGoogle = "Desconectar Google",
    connectGithub = "Conectar GitHub",
    disconnectGithub = "Desconectar GitHub",
    connected = "Conectado",
    notConnected = "Não conectado",
    appDiagnostics = "Diagnóstico do app",
    about = "Sobre o Ayanami Learn",
    logout = "Terminar sessão",
    completeYourProfile = "Complete seu perfil",
    profilePhoto = "Foto de perfil",
    changePhoto = "Alterar foto",
    statusOnline = "Online",
    statusIdle = "Inativo",
    statusOffline = "Offline",
    profileSaved = "Perfil guardado.",
    googleIdTokenMissing = "O token do Google não foi recebido.",
    googleSignInFailed = "Falha ao entrar com Google.",
    googleConnectedMessage = "Google conectado.",
    googleDisconnectedMessage = "Google desconectado.",
    githubConnectedMessage = "GitHub conectado.",
    githubDisconnectedMessage = "GitHub desconectado.",
    accountActionFailed = "A ação da conta falhou.",
    sessionRequired = "É necessário iniciar sessão para usar esta função.",
    authWelcomePrefix = "Bem-vindo ao",
    authTagline = "Aprenda inglês no seu próprio ritmo.",
    authEmail = "E-mail",
    authPassword = "Palavra-passe",
    authForgotPassword = "Esqueceste-te da palavra-passe?",
    authSignIn = "Entrar",
    authNoAccount = "Ainda não tens conta?",
    authCreateFreeAccount = "Criar Conta Gratuita",
    authSignInWithGoogle = "Entrar com Google",
    authCreateWithGoogle = "Criar conta com Google",
    authConnecting = "Conectando...",
    authLetsStart = "Vamos começar!",
    authAlmostThere = "Quase lá!",
    authStepOneDescription = "Cria o teu perfil para guardarmos o teu progresso.",
    authStepTwoDescription = "Define uma palavra-passe segura e confirma a tua língua nativa.",
    authFullName = "O teu nome",
    authContinue = "Continuar",
    authCreateAccount = "Criar Conta",
    authCreatingAccount = "Criando conta...",
    authPasswordResetEmailRequired = "Digite o e-mail para recuperar a palavra-passe.",
    authPasswordResetEmailSent = { "Enviamos um link de recuperação para $it." },
    authPasswordResetFailed = "Não foi possível enviar o e-mail de recuperação.",
    authFailed = "Falha na autenticação.",
    appVersion = { "Versão $it" },
    signedInAs = { "Sessão: $it" },
    firebaseSession = { if (it) "Firebase ativo" else "Firebase não autenticado" }
)

val UkrainianStrings = AppStrings(
    settings = "Налаштування",
    edit = "Редагувати",
    save = "Зберегти",
    profile = "Профіль",
    editProfile = "Редагувати профіль",
    displayName = "Ім'я користувача",
    bio = "Біографія",
    nativeLanguage = "Рідна мова",
    activityStatus = "Статус активності",
    rememberThisSetting = "Запам'ятати це налаштування",
    learning = "Навчання",
    preferences = "Налаштування",
    accountAndSupport = "Обліковий запис і підтримка",
    dailyGoal = "Щоденна ціль",
    minutesPerDay = { "$it хвилин на день" },
    voiceReplies = "Голосові відповіді",
    speakingExercises = "Вправи на мовлення",
    studyReminders = "Нагадування про навчання",
    soundEffects = "Звукові ефекти",
    darkMode = "Темна тема",
    ayanamiTheme = "Візуальна тема Ayanami",
    aiMode = "Режим ШІ",
    choosePractice = "Оберіть, як хочете практикуватися сьогодні",
    voiceAi = "Говорити з Ayanami Live",
    voiceAiDescription = "Жива голосова розмова в реальному часі",
    textAi = "Надіслати повідомлення",
    textAiDescription = "Практикуйте письмо й запитання в чаті",
    aiVoiceTile = "Голос наживо",
    aiChatTile = "Чат",
    ayanamiLive = "Ayanami Live",
    ayanamiLearnAi = "Ayanami Learn AI",
    messagePlaceholder = "Повідомлення...",
    viewProfile = "Переглянути профіль",
    voiceListening = "Слухаю...",
    voiceThinking = "Думаю...",
    voiceSpeaking = "Говорю",
    voiceConnecting = "Підключення",
    voiceReady = "Готово",
    startLesson = "ПОЧАТИ",
    voiceMic = "Мікрофон",
    voiceEnd = "Завершити",
    voiceHintReady = "Торкніться мікрофона й почніть говорити",
    voiceHintListening = "Торкніться ще раз, коли договорите",
    voiceHintSpeaking = "Торкніться мікрофона, щоб перервати",
    voiceHintConnecting = "Підключення до Ayanami...",
    settingsTab = "Налаштування",
    homeTab = "Шлях",
    practiceTab = "Практика",
    leaguesTab = "Ліги",
    aiTab = "ШІ",
    connectGoogle = "Підключити Google",
    disconnectGoogle = "Відключити Google",
    connectGithub = "Підключити GitHub",
    disconnectGithub = "Відключити GitHub",
    connected = "Підключено",
    notConnected = "Не підключено",
    appDiagnostics = "Діагностика застосунку",
    about = "Про Ayanami Learn",
    logout = "Вийти",
    completeYourProfile = "Заповніть профіль",
    profilePhoto = "Фото профілю",
    changePhoto = "Змінити фото",
    statusOnline = "Онлайн",
    statusIdle = "Неактивний",
    statusOffline = "Офлайн",
    profileSaved = "Профіль збережено.",
    googleIdTokenMissing = "Токен Google не отримано.",
    googleSignInFailed = "Не вдалося увійти через Google.",
    googleConnectedMessage = "Google підключено.",
    googleDisconnectedMessage = "Google відключено.",
    githubConnectedMessage = "GitHub підключено.",
    githubDisconnectedMessage = "GitHub відключено.",
    accountActionFailed = "Не вдалося виконати дію з обліковим записом.",
    sessionRequired = "Потрібно увійти, щоб скористатися цією функцією.",
    authWelcomePrefix = "Ласкаво просимо до",
    authTagline = "Вивчайте англійську у власному темпі.",
    authEmail = "Електронна пошта",
    authPassword = "Пароль",
    authForgotPassword = "Забули пароль?",
    authSignIn = "Увійти",
    authNoAccount = "Ще немає акаунта?",
    authCreateFreeAccount = "Створити безкоштовний акаунт",
    authSignInWithGoogle = "Увійти через Google",
    authCreateWithGoogle = "Створити акаунт через Google",
    authConnecting = "Підключення...",
    authLetsStart = "Почнімо!",
    authAlmostThere = "Майже готово!",
    authStepOneDescription = "Створіть профіль, щоб ми зберігали ваш прогрес.",
    authStepTwoDescription = "Задайте надійний пароль і підтвердьте рідну мову.",
    authFullName = "Ваше ім'я",
    authContinue = "Продовжити",
    authCreateAccount = "Створити акаунт",
    authCreatingAccount = "Створення акаунта...",
    authPasswordResetEmailRequired = "Введіть електронну пошту, щоб відновити пароль.",
    authPasswordResetEmailSent = { "Ми надіслали посилання для відновлення на $it." },
    authPasswordResetFailed = "Не вдалося надіслати лист для відновлення.",
    authFailed = "Помилка автентифікації.",
    appVersion = { "Версія $it" },
    signedInAs = { "Сесія: $it" },
    firebaseSession = { if (it) "Firebase активний" else "Firebase не автентифіковано" }
)

val RussianStrings = AppStrings(
    settings = "Настройки",
    edit = "Редактировать",
    save = "Сохранить",
    profile = "Профиль",
    editProfile = "Редактировать профиль",
    displayName = "Имя пользователя",
    bio = "Биография",
    nativeLanguage = "Родной язык",
    activityStatus = "Статус активности",
    rememberThisSetting = "Запомнить эту настройку",
    learning = "Обучение",
    preferences = "Предпочтения",
    accountAndSupport = "Аккаунт и поддержка",
    dailyGoal = "Ежедневная цель",
    minutesPerDay = { "$it минут в день" },
    voiceReplies = "Голосовые ответы",
    speakingExercises = "Упражнения на речь",
    studyReminders = "Напоминания об учебе",
    soundEffects = "Звуковые эффекты",
    darkMode = "Темная тема",
    ayanamiTheme = "Визуальная тема Ayanami",
    aiMode = "Режим ИИ",
    choosePractice = "Выберите, как хотите практиковаться сегодня",
    voiceAi = "Говорить с Ayanami Live",
    voiceAiDescription = "Живой голосовой разговор в реальном времени",
    textAi = "Отправить сообщение",
    textAiDescription = "Практикуйте письмо и вопросы в чате",
    aiVoiceTile = "Голос вживую",
    aiChatTile = "Чат",
    ayanamiLive = "Ayanami Live",
    ayanamiLearnAi = "Ayanami Learn AI",
    messagePlaceholder = "Сообщение...",
    viewProfile = "Посмотреть профиль",
    voiceListening = "Слушаю...",
    voiceThinking = "Думаю...",
    voiceSpeaking = "Говорю",
    voiceConnecting = "Подключение",
    voiceReady = "Готово",
    startLesson = "НАЧАТЬ",
    voiceMic = "Микрофон",
    voiceEnd = "Завершить",
    voiceHintReady = "Нажмите на микрофон и начните говорить",
    voiceHintListening = "Нажмите снова, когда закончите",
    voiceHintSpeaking = "Нажмите на микрофон, чтобы прервать",
    voiceHintConnecting = "Подключение к Ayanami...",
    settingsTab = "Настройки",
    homeTab = "Путь",
    practiceTab = "Практика",
    leaguesTab = "Лиги",
    aiTab = "ИИ",
    connectGoogle = "Подключить Google",
    disconnectGoogle = "Отключить Google",
    connectGithub = "Подключить GitHub",
    disconnectGithub = "Отключить GitHub",
    connected = "Подключено",
    notConnected = "Не подключено",
    appDiagnostics = "Диагностика приложения",
    about = "О Ayanami Learn",
    logout = "Выйти",
    completeYourProfile = "Заполните профиль",
    profilePhoto = "Фото профиля",
    changePhoto = "Изменить фото",
    statusOnline = "Онлайн",
    statusIdle = "Неактивен",
    statusOffline = "Офлайн",
    profileSaved = "Профиль сохранен.",
    googleIdTokenMissing = "Токен Google не получен.",
    googleSignInFailed = "Не удалось войти через Google.",
    googleConnectedMessage = "Google подключен.",
    googleDisconnectedMessage = "Google отключен.",
    githubConnectedMessage = "GitHub подключен.",
    githubDisconnectedMessage = "GitHub отключен.",
    accountActionFailed = "Не удалось выполнить действие с аккаунтом.",
    sessionRequired = "Чтобы использовать эту функцию, нужно войти.",
    authWelcomePrefix = "Добро пожаловать в",
    authTagline = "Учите английский в своем темпе.",
    authEmail = "Электронная почта",
    authPassword = "Пароль",
    authForgotPassword = "Забыли пароль?",
    authSignIn = "Войти",
    authNoAccount = "Еще нет аккаунта?",
    authCreateFreeAccount = "Создать бесплатный аккаунт",
    authSignInWithGoogle = "Войти через Google",
    authCreateWithGoogle = "Создать аккаунт через Google",
    authConnecting = "Подключение...",
    authLetsStart = "Начнем!",
    authAlmostThere = "Почти готово!",
    authStepOneDescription = "Создайте профиль, чтобы мы сохраняли ваш прогресс.",
    authStepTwoDescription = "Задайте надежный пароль и подтвердите родной язык.",
    authFullName = "Ваше имя",
    authContinue = "Продолжить",
    authCreateAccount = "Создать аккаунт",
    authCreatingAccount = "Создание аккаунта...",
    authPasswordResetEmailRequired = "Введите электронную почту, чтобы восстановить пароль.",
    authPasswordResetEmailSent = { "Мы отправили ссылку для восстановления на $it." },
    authPasswordResetFailed = "Не удалось отправить письмо для восстановления.",
    authFailed = "Ошибка аутентификации.",
    appVersion = { "Версия $it" },
    signedInAs = { "Сессия: $it" },
    firebaseSession = { if (it) "Firebase активен" else "Firebase не аутентифицирован" }
)

fun NativeLanguage.appStrings(): AppStrings {
    return when (this) {
        NativeLanguage.Portuguese -> PortugueseStrings
        NativeLanguage.Ukrainian -> UkrainianStrings
        NativeLanguage.Russian -> RussianStrings
    }
}

val LocalAppStrings = staticCompositionLocalOf { PortugueseStrings }
